version: "3.9"

services:
  employees-db:
    image: postgres:16
    container_name: employees-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_INTERNAL_PORT}"
    volumes:
      - employees_db_data:/var/lib/postgresql/data

  employees-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: employees-api
    restart: always
    depends_on:
      - employees-db
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@employees-db:${DB_INTERNAL_PORT}/${DB_NAME}?schema=public"
      AUTH_API_URL: ${AUTH_API_URL}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
    ports:
      - "8882:8882"

volumes:
  employees_db_data: