version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: lavanderia_db
    restart: always
    environment:
      # VARIABLES TRAÍDAS DEL ARCHIVO .env PRINCIPAL
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  servicios-api:
    build: 
      context: ./servicios-api
      dockerfile: Dockerfile
    container_name: api_servicios
    depends_on:
      - db
    ports:
      - "4001:3000"
    environment: 
      # Generamos la URL de conexión dentro del contenedor usando las variables de ENV
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      # Inyectamos el Secreto de Seguridad
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET} 
    volumes:
      # Hot Reload y mapeo de código
      - ./servicios-api/app:/usr/src/app
      - /usr/src/app/node_modules

  clientes-api:
    build: 
      context: ./clientes-api
      dockerfile: Dockerfile
    container_name: api_clientes
    depends_on:
      - db  
    ports:
      - "4002:3000" 
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
    volumes:
      - ./clientes-api/app:/usr/src/app
      - /usr/src/app/node_modules

  ordenes-api:
    build: 
      context: ./ordenes-api  
      dockerfile: Dockerfile
    container_name: api_ordenes
    depends_on:
      - db  
    ports:
      - "4003:3000"
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
    volumes:
      - ./ordenes-api/app:/usr/src/app
      - /usr/src/app/node_modules